#!/bin/sh

mv /tmp/stein17/skin.xml /usr/lib/enigma2/python/Plugins/Extensions/AdvancedMovieSelection/skin/skin.xml

echo "                                                          						"
echo "  "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                           	 "
echo "...Ultimate HD Skin for AdvancedMovieSelection by stein17 successful installed."
echo "                                                                               " 
echo "                                                                               "
echo "                                                                               "
exit 0

