#!/bin/sh

mv /tmp/stein/SkyAddedEdit.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyAddedEdit.py
mv /tmp/stein/SkyChannelEditor.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyChannelEditor.py
mv /tmp/stein/SkyChannelSelect.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyChannelSelect.py
mv /tmp/stein/SkyGenreSelect.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyGenreSelect.py
mv /tmp/stein/SkyRecorderArchiv.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyRecorderArchiv.py
mv /tmp/stein/SkyRecorderMainScreen.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyRecorderMainScreen.py
mv /tmp/stein/SkyRecorderSettings.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyRecorderSettings.py
mv /tmp/stein/SkySkipWordsSelect.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkySkipWordsSelect.py
mv /tmp/stein/SkyWhitelist.py /usr/lib/enigma2/python/Plugins/Extensions/skyrecorder/SkyWhitelist.py

echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "  The Skyrecorder-FHD-Skins-by-stein17 is now being installed...           "
echo "                                                                           " 
echo "                                                                           "
echo "                                                                           "
exit 0
