#!/bin/sh

echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "          Skyrecorder-FHD-Skins-by-stein17 is now being removed...         "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
echo "                                                                           "
exit 0
