#!/bin/sh

echo "                                                          						"
echo "  "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                               "
echo "                                                                           	 "
echo "...Steampunk HD Skin for AdvancedMovieSelection by stein17 successful installed."
echo "                                                                               " 
echo "                                                                               "
echo "                                                                               "
exit 0

